### ISSUE TITLE
Home Page - Ramo's Thoughts

### ISSUE THREAD

**Issue by ramonabolboaca13** [ramonabolboaca13/blog-comments#2]
https://www.ramonabolboaca.com/2020/05/02/hello-world/#post-footer 

 Welcome to my page. This site is under construction.

**Comment by ramonabolboaca13** [comment]
My first comment.

**Comment by ramonabolboaca13** [comment]
First comment.

**Comment by cilica** [comment]
Second comment.

**Comment by MopTopZop** [comment]
What kind of paint did you use?

**Comment by ramonabolboaca13** [comment]
> @MopTopZop
> What kind of paint did you use?
> 

I used a local Romanian product "OSKAR Direct pe faianta": https://www.dedeman.ro/ro/vopsea-direct-pe-faianta-oskar-interior-pe-baza-de-apa-albastru-topaz-0-6-l/p/5013844.

Any type of water-based paint for ceramics should be OK.
